#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Appdash
  # forward declarations
  class CollectPacket < ::ProtocolBuffers::Message; end

  class CollectPacket < ::ProtocolBuffers::Message
    # forward declarations
    class SpanID < ::ProtocolBuffers::Message; end
    class Annotation < ::ProtocolBuffers::Message; end

    set_fully_qualified_name "appdash.CollectPacket"

    # nested messages
    class SpanID < ::ProtocolBuffers::Message
      set_fully_qualified_name "appdash.CollectPacket.SpanID"

      required :fixed64, :trace, 2
      required :fixed64, :span, 3
      optional :fixed64, :parent, 4
    end

    class Annotation < ::ProtocolBuffers::Message
      set_fully_qualified_name "appdash.CollectPacket.Annotation"

      required :string, :key, 6
      optional :bytes, :value, 7
    end

    required ::Appdash::CollectPacket::SpanID, :spanid, 1, :group => true
    repeated ::Appdash::CollectPacket::Annotation, :annotation, 5, :group => true
  end

end
